services:
  sgroup13:
    build: .
    image: igroup13
    container_name: cdevops13
    ports:
      - "80:80"
    volumes:
      - ./codi/:/var/www/html
    networks:
      - xarxa13

networks:
  xarxa13:
    driver: bridge
